name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          npm install -g mocha chai selenium-webdriver chromedriver 

      - name: Install eslint and plugins
        run: |
          npm install -g eslint eslint-config-google eslint-plugin-jsdoc
      
      - name: Build and test extension
        env:
          CHROME_BIN: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
        run: |
           mocha src/tests/test.js

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage/lcov.info
